# Generated by Django 5.0.6 on 2024-06-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatars/92061424.png', upload_to='avatars/'),
        ),
    ]
