# Generated by Django 5.0.6 on 2024-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='blog',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/'),
        ),
    ]
