# Generated by Django 5.0.6 on 2024-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_content_blog_discription_blog_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uri',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
