# Generated by Django 5.0.6 on 2024-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
