# Generated by Django 5.0.6 on 2024-06-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
