# Generated by Django 5.0.6 on 2024-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_category_alter_blog_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text_file',
            field=models.FileField(default='blog/default.md', upload_to='blog/'),
        ),
    ]
