# Generated by Django 5.0.6 on 2024-06-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_text_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription',
            new_name='description',
        ),
    ]
