# Generated by Django 5.0.6 on 2024-07-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_discription_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text_file',
        ),
    ]
