# Generated by Django 5.0.6 on 2024-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_blog_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='files',
            field=models.FilePathField(allow_folders=True, default='', path='blog'),
        ),
    ]
