# Generated by Django 5.0.6 on 2024-07-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
