import Nav from "@/components/nav/nav";
import type { Metadata } from "next";
import "./globals.css";
import style from "./page.module.scss";
import "katex/dist/katex.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={style.body}>
        <Nav />
        <main className={style.main}>{children}</main>
      </body>
    </html>
  );
}
