import Nav from "@/components/nav/nav";
import "katex/dist/katex.min.css";
import type { Metadata } from "next";
import "./globals.css";
import style from "./page.module.scss";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={style.body}>
        <Providers>
          <Nav />
          <main className={style.main}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
