import Nav from "@/components/nav/nav";
import Tools from "@/components/tools/tools";
import type { Metadata } from "next";

import Providers from "@/app/providers";
import style from "./page.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={style.body}>
        <Providers>
          <Nav />
          <main className={style.main}>{children}</main>
          <Tools />
        </Providers>
      </body>
    </html>
  );
}
