name: Continuous Deployment


on:
  push:
    branches: [cd]
  pull_request:
    branches: [cd]

jobs:
  cd:
    environment: DJANGO_ALLOWED_HOSTS
    runs-on: ubuntu-latest
    steps:
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: wireguard-${{ runner.os }}-apt-${{ hashFiles('**/setup.sh') }}
          restore-keys: |
            wireguard-${{ runner.os }}-apt-

      - name: Install WireGuard client
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Setup WireGuard Configuration
        run: |
          umask 077
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_CLIENT_PRIVATE_KEY }}
          Address = 10.253.0.2/32

          [Peer]
          PresharedKey = ${{ secrets.WG_PRESHARED_KEY }}
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          Endpoint = ${{ secrets.WG_SERVER_ENDPOINT }}
          AllowedIPs = 10.253.0.1/32, 192.168.1.0/24" | sudo tee /etc/wireguard/wg0.conf

      - name: Start WireGuard Client
        run: |
          sudo wg-quick up wg0
          sleep 5

      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: my-django-app
      #     path: my-django-app.tar.gz

      # - name: Download Next.js artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: my-nextjs-app
      #     path: my-nextjs-app.tar.gz

      - name: make dummy files
        run: echo "dummy" > dummy.txt

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dummy.txt"
          target: ${{ secrets.SERVER_PATH }} 
          

      - name: SSH into server using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            echo "Commit hash: $(git rev-parse HEAD)" >> commit.txt
            bash deploy.sh
